# Generated by Django 3.2.3 on 2021-05-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_termino',
            field=models.DateTimeField(),
        ),
    ]
